### ISSUE TITLE
Unsub teilweise ohne Funktion

### ISSUE THREAD

**Issue by zapfdk** [zapfdk/tui-mensa-bot#2]
siehe Titel

**Comment by thb42** [comment]
Welche Funktionen fehlt denn bzw. sind unvollständig?

**Comment by zapfdk** [comment]
Das Unsubscriben hat bei jemandem nicht funktioniert, hat den Speiseplan trotzdem bekommen. Ich konnte das allerdings nicht reproduzieren, lag vermutlich einfach an dem Disconnect Problem, siehe #1

**Comment by thb42** [comment]
D.h. man kann dieses Issue schließen?

**Comment by zapfdk** [comment]
Jop, erstmal schon.
